### ISSUE TITLE
Table style

### ISSUE THREAD

**Issue by egoist** [egoist/docup#13]

**Comment by zhw2590582** [comment]
I am waiting for this

**Comment by egoist** [comment]
I won't have time to implement this till next month, this should be easy to add so PR is welcome 😉

**Comment by arackaf** [comment]
Hey all - if anyone is wanting table styles, please remember there's nothing preventing you from just dropping your own css file into your repo's `docs` folder, linking it from index.html, and adding some rudimentary styles. 

I'm terribly lacking in design skills, but after 20 minutes of poking around I came up with this

```css
table {
  font-size: .95rem;
}
table code {
  font-size: .85rem;
}

table > thead > tr > th { 
  border-bottom: 2px solid var(--navbar-bg);
}

table > tbody > tr > td { 
  border-bottom: 1px solid var(--sidebar-bg);
}
table > tbody > tr > td:not(:last-child) { 
  border-right: 1px solid var(--sidebar-bg);
}

table > tbody > tr > td:first-child { 
  padding-right: 5px;
}
table > tbody > tr > td:not(:first-child) { 
  padding-left: 5px;
}

table code { 
  background: unset;
  padding: unset;
}
```

which is shown below. I'm sure egoist will come up with something better when he gets around to it, but something like the above should be a solid workaround until then. 

![image](https://user-images.githubusercontent.com/11261266/82710168-dc3fc800-9c47-11ea-90ff-6850b967a107.png)
